### ISSUE TITLE
More resilient manifest application

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#1814]
### Is your feature request related to a problem? Please describe.

The [Manifest Deployer](https://docs.k0sproject.io/v1.23.6+k0s.2/manifests/) part of k0s could be more resilient and its performance relies on the current way in which components are initialized and run, even if it shouldn't matter.

* [x] Sometimes new stacks are missed: #1781
* [x] fsnotify events trigger a stack application even if those files would be ignored by the applier later on: #1815
* [ ] Files are written directly into the manifest folders, without any precautions that there might be files that are not fully written yet. This leads to situations where the stack applier behaves strangely (3845479a0): #1816

### Describe the solution you would like

Refactor the code to iron out edge cases.

### Describe alternatives you've considered

Leave it as is. Works 99% of the time. The 1% will be hard to debug.
