### ISSUE TITLE
Instrument components with events and health-checks, meta-issue

### ISSUE THREAD

**Issue by mikhail-sakhnov** [k0sproject/k0s#2532]
Since #2458 we have a sub-system to debug cluster state.

Components might produce events.
Components might have health-checks (periodical). 

At the moment, the PR with tooling for events and checks is merged, though non of the components actually use health-checks or produce events but KonnectivityComponent (https://github.com/k0sproject/k0s/blob/main/pkg/component/controller/konnectivity.go), just as an example. 

The example of emitting event https://github.com/k0sproject/k0s/blob/main/pkg/component/controller/konnectivity.go#L174
The example of emitting event without payload https://github.com/k0sproject/k0s/blob/main/pkg/component/controller/konnectivity.go#L275
Both Emit and EmitWithPayload are implemented in embedded structure *prober.EventEmitter, init example https://github.com/k0sproject/k0s/blob/main/cmd/controller/controller.go#L451

The example of Healthy implementation https://github.com/k0sproject/k0s/blob/main/pkg/component/controller/konnectivity.go#L222

The events and statuses are available under new subcommand:
```
sudo ./k0s status components
```

This issue is supposed to be an umbrella issue to track, which component we want to instrument.

My suggestion is to keep a single issue, but create separate PR for each component.

Components list
Controller:
- [ ] controller/leaderelector/leasepool.go
- [ ] controller/k0scloudprovider.go
- [ ] controller/metricserver.go
- [ ] controller/calico.go
- [ ] controller/apiserver.go
- [ ] controller/clusterConfig.go
- [ ] controller/kine.go
- [ ] controller/systemrbac.go
- [ ] controller/autopilot.go
- [ ] controller/extensions_controller.go
- [ ] controller/coredns.go
- [ ] controller/csrapprover.go
- [ ] controller/controllersleasecounter.go
- [ ] controller/kubeproxy.go
- [ ] controller/tunneledapiendpointreconciller.go
- [ ] controller/kuberouter.go
- [ ] controller/crd.go
- [ ] controller/metrics.go
- [ ] controller/scheduler.go
- [ ] controller/noderole.go
- [ ] controller/apiendpointreconciler.go
- [ ] controller/manifests.go
- [ ] controller/etcd.go

Worker
- [ ] worker/ocibundle.go
- [ ] worker/containerd.go
- [ ] worker/cri_runtime.go
- [ ] worker/static_pods.go
- [ ] worker/certificate_manager.go
- [ ] worker/autopilot.go
