### ISSUE TITLE
Epic: Windows worker restoration

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [k0sproject/k0s#2568]
Seems like this is much more complicated than I think. There are several things we need to fix before it is working again.

First step is to let kubelet/kube-proxy run correctly on Windows worker again, this is an ongoing issue under investigation.

Next step should be adding back the missing Dockershim altogether. We could either use:

cri-dockerd: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/

Directly use containerd in Windows. We already have a scoop bucket available: https://github.com/rivy/scoop.bucket.scoop-main/blob/master/containerd.json

The first method should work out of the box with Mirantis and Docker Desktop with minimal changes, while the latter will be more formal and correct but will require significantly more code changes than former, relatively speaking of course.

Notice: you can just install [Docker Engine on Windows with chocolatey](https://community.chocolatey.org/packages/docker-engine). It will support Windows Container mode only, however. But this opens the door for most Windows 10 to run k0s.

# Related

#2460 
#2567

**Comment by jnummelin** [comment]
With 1.28 containerd is now bundled with k0s: https://github.com/k0sproject/k0s/pull/3174

Calico also is setup by k0s using normal daemonset way: https://github.com/k0sproject/k0s/pull/3209

@wizpresso-steve-cy-fan we appreciate if you could give it a spin to see if the original issues are now solved.

Like @twz123 mentioned, CI is something we need to still figure out, till now we've only done manual testing for Windows.

**Comment by twz123** [comment]
Alright! Here's a plan to make k0s actually usable on Windows (again):

(The below order is not necessarily chronological.)

* Support for running as a Windows service
  This enables a few other things: Firstly, the Windows service facility is kinda the init system of Windows, and it's the usual way to start background tasks after a a machine has booted up. `k0s install` is already able to install k0s as a Windows service, but `k0s worker' doesn't establish a control connection to the Windows service manager, and therefore doesn't play nicely with it. As a side effect, running as a service also means that the k0s worker process itself has the rights to log in a local user without a password, which is the main reason for running containerd as a service, as this right is needed to run containers as different users. If k0s itself is run as a service, it can pass this right to containerd, even if it's run as a simple supervised process. This simplifies the implementation of the containerd component, which doesn't need to be implemented differently on Windows.

* Add some useful sysprobes for Windows
  Most importantly, k0s needs a sysprobe to check if it has the above-mentioned right to logon users without passwords. This will allow `k0s worker` to be fail-fast for "manual" invocations, e.g. from an "administrator terminal" that doesn't have sufficient rights.

* Implement logging differently when running as a Windows service
  Windows services cannot use stdout and stderr for logging. These streams are discarded and not collected at all by Windows. K0s needs to adapt to this. The simplest solution to get things going would be to set up a simple log file, say in `<data-dir>/k0s.log`, and have the k0s log output go there. The path to the log file could be automatically determined during `k0s install` and passed to the k0s service process via an environment variable, so that it's easily available in the early stages of k0s startup, when the command line flags have not yet been parsed. There's probably more to "production-grade" logging (log rotation, retention, compression, whatever...), maybe k0s could even use Event Tracing for Windows instead of plain old log files. That's a thing to think about for the future us.

* Have a way to run the [Windows Operational Readiness] tests
  Just as the k0s CI runs the Kubernetes conformance test suite in several places, we should do something similar for the Windows Operational Readiness test suite, which is sort of the Windows counterpart to the standard conformance tests that were implemented with Linux in mind. The "WOR" test suite is likely to uncover many compatibility issues, which can then be addressed one at a time.

* Windows support for kubectl
  The k0s OS tests use k0sctl to create clusters on infra provided by AWS. I have added initial Windows support to the OS test suite. This may be helpful in implementing proper Windows support in k0sctl, so that Windows clusters can be provisioned in the same way as Linux clusters. Such clusters could then be used as targets for the Windows Operational Readiness tests.

[Windows Operational Readiness]: https://github.com/kubernetes-sigs/windows-operational-readiness

**Comment by twz123** [comment]
> Concerning CI: We could try to hack on some (probably ugly) GH workflow that tries to bring up a Windows worker somehow on a GH Windows runner and see how far we get with that.

I have an [experimental branch on my fork](https://github.com/twz123/k0s/tree/win-wsl) where I'm trialing this a bit. TL;DR: It works. On a single Windows GitHub runner, we can run a controller+worker node in WSL, and then attach a Windows worker to that control plane. The Windows node actually becomes ready, but, when deploying actual workloads, the Calico networking is still erroring out when setting up the pod network.

After poking at Windows support for quite some time now, I found many things that need to be fixed, but none of them is a real blocker. I only see one big obstacle where we need to figure out how to deal with: Calico networking. Nowadays, Tigera only supports the operator-based installation method for Calico, whereas k0s deploys Calico "the hard way" using deployment manifests. For Linux, this is workable since upstream still provides up to date deployment manifests for reference. For Windows, on the other hand, such manifests aren't provided, and the documentation simply states "Use the operator." We need to figure out what to do about this.

**Comment by jnummelin** [comment]
We've been working on this with @twz123 , I focused mainly on the part to get Calico manifests for windows. Building on top of Toms branch, I have my own [experimental branch](https://github.com/jnummelin/k0s/tree/calico-win-manifests) on my fork.

This actually does get Calico up-and-running on windows and pods are able to cross-connect.
```
[root@ip-172-31-26-139 ~]# k0s kc get node,pod,svc -o wide
NAME                                               STATUS   ROLES           AGE    VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION                     CONTAINER-RUNTIME
node/ec2amaz-0np0h8g                               Ready    <none>          141m   v1.34.0-beta.0+k0s   172.31.29.89    <none>        Windows Server 2022 Datacenter   10.0.20348.3932                    containerd://1.7.27
node/ip-172-31-26-139.eu-west-1.compute.internal   Ready    control-plane   141m   v1.34.0-beta.0+k0s   172.31.26.139   <none>        Amazon Linux 2023.8.20250818     6.1.147-172.266.amzn2023.aarch64   containerd://1.7.27

NAME                               READY   STATUS    RESTARTS   AGE   IP               NODE                                          NOMINATED NODE   READINESS GATES
pod/iis-windows-9787d48c7-5wh2j    1/1     Running   0          19m   10.244.208.196   ec2amaz-0np0h8g                               <none>           <none>
pod/nginx-linux-7cd76796dd-j4hrz   1/1     Running   0          26m   10.244.72.195    ip-172-31-26-139.eu-west-1.compute.internal   <none>           <none>

NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE    SELECTOR
service/iis-windows-svc   ClusterIP   10.110.142.181   <none>        80/TCP    27m    app=iis-windows
service/kubernetes        ClusterIP   10.96.0.1        <none>        443/TCP   142m   <none>
service/nginx-linux-svc   ClusterIP   10.110.146.185   <none>        80/TCP    26m    app=nginx-linux
```
Connecting from nginx-linux pod to IIS via svc works:
```
[root@ip-172-31-26-139 ~]# k0s kubectl exec -it nginx-linux-7cd76796dd-j4hrz -- sh -c 'curl -s -o /dev/null -w "%{http_code}\n" http://10.110.142.181:80/'
200
```
IIS --> nginx-linux also works:
```
[root@ip-172-31-26-139 ~]# k0s kubectl exec -it iis-windows-9787d48c7-5wh2j -- powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
                                                                                                                                                                                                       Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows                                                                                                                                                                                                                                                                                                                                                                                                                              
PS C:\> $u='http://10.110.146.185:80/'; (Invoke-WebRequest $u -UseBasicParsing).StatusCode
200

```

**Comment by twz123** [comment]
The most important parts of this shipped in 1.34. So Windows workers are a thing again! Just try this:

```pwsh
Install-WindowsFeature -Name Containers
$src = "https://github.com/k0sproject/k0s/releases/download/v1.34.1%2Bk0s.0/k0s-v1.34.1+k0s.0-amd64.exe"
$dst = Join-Path $env:LOCALAPPDATA 'Microsoft/WindowsApps/k0s.exe'
Invoke-WebRequest -ProgressAction SilentlyContinue -Uri $src -OutFile $dst
& k0s install worker --token-file ./worker-token
& k0s start
```

Concerning https://github.com/k0sproject/k0s/issues/2568#issuecomment-2681755096:

* [x] Support for running as a Windows service
  #6448
* [ ] Add some useful sysprobes for Windows
  That's a quality of life thing. Definitely on the agenda, but with less priority.
  #6778
* [x] Implement logging differently when running as a Windows service
  An initial naive implementation for simple log files is in #6448.
  Some integration with the Windows Event Log or ETW is yet to come.
* [x] Windows support for k0sctl
  @kke is pushing for it: k0sproject/k0sctl#936
* [x] A CI job for Windows, as mentioned in https://github.com/k0sproject/k0s/issues/2568#issuecomment-1477755593
  There's @jnummelin's [experimental branch](https://github.com/jnummelin/k0s/tree/calico-win-manifests). Planning to push this over the finish line and backport this to 1.34.
  #6764
* [ ] Have a way to run the Windows Operational Readiness tests
  That'd be the ultimate end goal.

As always, if anybody is interested in pushing it further, PRs are much appreciated!

**Comment by twz123** [comment]
IMO Windows support has come a long way in k0s recently. In 1.36, we will support both konnectivity and NLLB (via Traefik), and we have at least some CI coverage for this. There's still some things to be done, mostly to improve the UX, but the core functionality is there. Closing this as completed.
